### PR TITLE
Update and add books

### PR DESCRIPTION
**Pull request by Feowerleaf**
This will add:
1. 音樂啟蒙 (jm1/junior music.pdf)
2. 《商業學》第一冊（2024） (sm1/businessstudies_2024.pdf)
3. 《經濟學》第一冊（2024年使用） (sm1/economics_2024.pdf)
4. 《高級數學》高一上冊（2024年使用） (sm1/addmaths1_2024.pdf)

This also update:
高中《物理好幫手》 (sm1/physics companion.pdf)

### CODE REVIEW

**Comment by melvinchia3636** [comment]
Please update the metadata in https://github.com/melvinchia3636/textbookLibrary/tree/a2b1cab71c94ff60ec4070f862c2aad596b56934/src/data as well

**Comment by Feowerleaf** [comment]
Sure, it is my pleasure to help.

There is also a book (高中《美術賞析》第三冊) which half chapters and cover page are not found. Do you want to add it?

**Comment by melvinchia3636** [comment]
> Sure, it is my pleasure to help.
> 
> There is also a book (高中《美術賞析》第三冊) which half chapters and cover page are not found. Do you want to add it?

Yeah sure!

**Comment by Feowerleaf** [comment]
There are some books which are in newer version, would you like to keep the old books, or just replace them?

**Comment by melvinchia3636** [comment]
> There are some books which are in newer version, would you like to keep the old books, or just replace them?

Let's keep both versions, since there are still students who are studying base on those old textbooks.

**Comment by Feowerleaf** [comment]
All right.

I can see your files are smaller, did you compress them?

**Comment by melvinchia3636** [comment]
nope, I scrape them from dongzong website,  combine the pictures into a single pdf file, and upload them as is.

**Comment by Feowerleaf** [comment]
I see, then I am going to upload some files which size are multiplied by 2 or 3
Well I did compress a few pages if they occupy space more than 100MB
Just feeling that it takes too much space for people who want to save and use them

**Comment by melvinchia3636** [comment]
No problem, go ahead. 

In my point of view, smaller file size might be more convenient to save and use, but might lead to blurry pages.

**Pull request merged**
